"""
Public-import boundary tests for PR-05 artifacts.

No file generated by workflow init, policy init, or the migration examples
may import from aigc._internal.
"""

import ast
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent
EXAMPLES_MIGRATION = REPO_ROOT / "examples" / "migration"


def _assert_no_internal_imports(source: str, label: str) -> None:
    """Parse source and assert no aigc._internal imports."""
    tree = ast.parse(source)
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            for alias in node.names:
                assert "_internal" not in alias.name, (
                    f"{label}: direct _internal import: {alias.name}"
                )
        elif isinstance(node, ast.ImportFrom):
            module = node.module or ""
            assert "_internal" not in module, (
                f"{label}: from-import from _internal: {module}"
            )


class TestMigrationExamplesBoundary:
    def test_invocation_only_no_internal_imports(self):
        source = (EXAMPLES_MIGRATION / "invocation_only.py").read_text()
        _assert_no_internal_imports(source, "invocation_only.py")

    def test_workflow_adoption_no_internal_imports(self):
        source = (EXAMPLES_MIGRATION / "workflow_adoption.py").read_text()
        _assert_no_internal_imports(source, "workflow_adoption.py")


class TestGeneratedStartersBoundary:
    """Generated starter content must not contain _internal imports."""

    def test_minimal_starter_workflow_py_no_internal(self):
        from aigc._internal.starter_templates import render_minimal_starter
        source = render_minimal_starter()["workflow_example.py"]
        _assert_no_internal_imports(source, "minimal/workflow_example.py")

    def test_standard_starter_workflow_py_no_internal(self):
        from aigc._internal.starter_templates import render_standard_starter
        source = render_standard_starter()["workflow_example.py"]
        _assert_no_internal_imports(source, "standard/workflow_example.py")

    def test_regulated_starter_workflow_py_no_internal(self):
        from aigc._internal.starter_templates import render_regulated_starter
        source = render_regulated_starter()["workflow_example.py"]
        _assert_no_internal_imports(source, "regulated/workflow_example.py")


class TestPresetsModuleBoundary:
    def test_aigc_presets_importable_without_internal(self):
        import aigc.presets as m
        assert hasattr(m, "MinimalPreset")
        assert hasattr(m, "StandardPreset")
        assert hasattr(m, "RegulatedHighAssurancePreset")
