"""
Thin preset builders for workflow starters.

Presets compile to ordinary policy YAML + session metadata.
They do not add runtime enforcement or hide host orchestration.
"""

from __future__ import annotations

from pathlib import Path


class MinimalPreset:
    """Minimal governance preset: role-only policy, 2-step workflow pattern."""

    PROFILE = "minimal"

    def __init__(self, role: str = "ai-assistant") -> None:
        self.role = role

    @property
    def policy_yaml(self) -> str:
        """Return valid YAML content for a minimal governance policy."""
        import yaml
        header = (
            "# Minimal AIGC governance policy\n"
            f"# Profile: {self.PROFILE} | Generated by: aigc workflow init\n"
        )
        data = {"policy_version": "1.0", "roles": [self.role]}
        return header + yaml.dump(data, default_flow_style=False)

    @property
    def session_metadata(self) -> dict:
        """Return metadata dict to pass to AIGC.open_session(metadata=...)."""
        return {
            "starter_profile": self.PROFILE,
            "generated_by": "aigc workflow init",
        }

    def write_policy(self, path: str | Path) -> None:
        """Write policy YAML to a file."""
        Path(path).write_text(self.policy_yaml, encoding="utf-8")


class StandardPreset:
    """Standard governance preset: role-only policy, approval-checkpoint pattern."""

    PROFILE = "standard"

    def __init__(self, role: str = "ai-assistant") -> None:
        self.role = role

    @property
    def policy_yaml(self) -> str:
        import yaml
        header = (
            "# Standard AIGC governance policy\n"
            f"# Profile: {self.PROFILE} | Generated by: aigc workflow init\n"
        )
        data = {"policy_version": "1.0", "roles": [self.role]}
        return header + yaml.dump(data, default_flow_style=False)

    @property
    def session_metadata(self) -> dict:
        return {
            "starter_profile": self.PROFILE,
            "generated_by": "aigc workflow init",
        }

    def write_policy(self, path: str | Path) -> None:
        Path(path).write_text(self.policy_yaml, encoding="utf-8")


class RegulatedHighAssurancePreset:
    """Regulated High Assurance preset: tool budget + source-required pattern."""

    PROFILE = "regulated-high-assurance"

    def __init__(self, role: str = "ai-assistant") -> None:
        self.role = role

    @property
    def policy_yaml(self) -> str:
        import yaml
        header = (
            "# Regulated High Assurance AIGC governance policy\n"
            f"# Profile: {self.PROFILE} | Generated by: aigc workflow init\n"
        )
        data = {
            "policy_version": "1.0",
            "roles": [self.role],
            "tools": {
                "allowed_tools": [
                    {"name": "document_reader", "max_calls": 3}
                ]
            },
        }
        return header + yaml.dump(data, default_flow_style=False)

    @property
    def session_metadata(self) -> dict:
        return {
            "starter_profile": self.PROFILE,
            "generated_by": "aigc workflow init",
        }

    def write_policy(self, path: str | Path) -> None:
        Path(path).write_text(self.policy_yaml, encoding="utf-8")
