"""
Starter template content for aigc workflow init.

Each render_*_starter() function returns {filename: content} for a profile.
All generated content uses public aigc imports only.
"""

from __future__ import annotations

from aigc._internal.presets import (
    MinimalPreset,
    StandardPreset,
    RegulatedHighAssurancePreset,
)


# ---------------------------------------------------------------------------
# Minimal profile
# ---------------------------------------------------------------------------

_MINIMAL_WORKFLOW_PY = '''\
"""
Minimal AIGC workflow example.

Generated by: aigc workflow init --profile minimal

Run:
    python workflow_example.py

Demonstrates a 2-step governed workflow using public AIGC APIs.
No external model API required -- uses a simulated model call.
"""
import aigc


def _simulate_model_call(prompt: str) -> dict:
    """Simulated model response. Replace with your real model call."""
    return {"result": f"Response to: {prompt[:60]}"}


def run_minimal_workflow(policy_file: str = "policy.yaml") -> dict:
    """Run a 2-step governed workflow. Returns the workflow artifact."""
    governance = aigc.AIGC()

    with governance.open_session(policy_file=policy_file) as session:
        # --- Step 1 ---
        pre1 = session.enforce_step_pre_call({
            "policy_file": policy_file,
            "input": {"prompt": "Analyze the document."},
            "output": {},
            "context": {},
            "model_provider": "anthropic",
            "model_identifier": "claude-sonnet-4-6",
            "role": "__AIGC_ROLE__",
        })
        output1 = _simulate_model_call("Analyze the document.")
        session.enforce_step_post_call(pre1, output1)

        # --- Step 2 ---
        pre2 = session.enforce_step_pre_call({
            "policy_file": policy_file,
            "input": {"prompt": "Summarize the findings."},
            "output": {},
            "context": {},
            "model_provider": "anthropic",
            "model_identifier": "claude-sonnet-4-6",
            "role": "__AIGC_ROLE__",
        })
        output2 = _simulate_model_call("Summarize the findings.")
        session.enforce_step_post_call(pre2, output2)

        session.complete()

    return session.workflow_artifact


if __name__ == "__main__":
    artifact = run_minimal_workflow()
    print(f"Status:  {artifact[\'status\']}")
    print(f"Steps:   {len(artifact[\'steps\'])}")
    print(f"Session: {artifact[\'session_id\']}")
'''

_MINIMAL_README_MD = """\
# Minimal Governance Starter

Generated by `aigc workflow init --profile minimal`.

## Run

```bash
python workflow_example.py
```

Expected output:
```
Status:  COMPLETED
Steps:   2
Session: <uuid>
```

## What this demonstrates

- 2-step governed workflow using `GovernanceSession`
- `enforce_step_pre_call` / `enforce_step_post_call` pattern
- Workflow artifact with `COMPLETED` status and correlated step checksums

## Customize

1. Replace `_simulate_model_call()` with your real model API call
2. Edit `policy.yaml` to add roles, pre-conditions, or output schema constraints
3. See the AIGC migration guide at
   https://github.com/nealsolves/aigc/blob/develop/docs/migration.md
   to migrate existing invocation-only governance
"""


def render_minimal_starter(role: str = "ai-assistant") -> dict[str, str]:
    """Return {filename: content} for the minimal starter profile."""
    preset = MinimalPreset(role=role)
    return {
        "policy.yaml": preset.policy_yaml,
        "workflow_example.py": _MINIMAL_WORKFLOW_PY.replace("__AIGC_ROLE__", role),
        "README.md": _MINIMAL_README_MD,
    }


# ---------------------------------------------------------------------------
# Standard profile (approval checkpoint)
# ---------------------------------------------------------------------------

_STANDARD_WORKFLOW_PY = '''\
"""
Standard AIGC workflow example -- approval checkpoint.

Generated by: aigc workflow init --profile standard

Run:
    python workflow_example.py

Demonstrates a 3-step governed workflow with a human approval checkpoint
(PAUSED state). No external model API required.
"""
import aigc


def _simulate_model_call(prompt: str) -> dict:
    """Simulated model response. Replace with your real model call."""
    return {"result": f"Response to: {prompt[:60]}"}


def _request_human_approval(summary: str) -> bool:
    """Simulate human approval. Replace with your real approval flow."""
    print(f"  [Approval requested] {summary}")
    print("  [Approval simulated] -> APPROVED")
    return True


def run_standard_workflow(policy_file: str = "policy.yaml") -> dict:
    """Run a 3-step workflow with approval checkpoint. Returns workflow artifact."""
    governance = aigc.AIGC()

    with governance.open_session(policy_file=policy_file) as session:
        # --- Step 1: Pre-approval work ---
        pre1 = session.enforce_step_pre_call({
            "policy_file": policy_file,
            "input": {"prompt": "Draft a proposal for review."},
            "output": {},
            "context": {"phase": "pre-approval"},
            "model_provider": "anthropic",
            "model_identifier": "claude-sonnet-4-6",
            "role": "__AIGC_ROLE__",
        })
        output1 = _simulate_model_call("Draft a proposal for review.")
        session.enforce_step_post_call(pre1, output1)

        # --- Approval checkpoint ---
        session.pause()  # OPEN -> PAUSED
        approved = _request_human_approval(output1["result"])
        if not approved:
            session.cancel()
            return session.finalize()
        session.resume()  # PAUSED -> OPEN

        # --- Step 2: Post-approval work ---
        pre2 = session.enforce_step_pre_call({
            "policy_file": policy_file,
            "input": {"prompt": "Finalize the approved proposal."},
            "output": {},
            "context": {"phase": "post-approval"},
            "model_provider": "anthropic",
            "model_identifier": "claude-sonnet-4-6",
            "role": "__AIGC_ROLE__",
        })
        output2 = _simulate_model_call("Finalize the approved proposal.")
        session.enforce_step_post_call(pre2, output2)

        # --- Step 3: Summary ---
        pre3 = session.enforce_step_pre_call({
            "policy_file": policy_file,
            "input": {"prompt": "Generate final summary."},
            "output": {},
            "context": {"phase": "summary"},
            "model_provider": "anthropic",
            "model_identifier": "claude-sonnet-4-6",
            "role": "__AIGC_ROLE__",
        })
        output3 = _simulate_model_call("Generate final summary.")
        session.enforce_step_post_call(pre3, output3)

        session.complete()

    return session.workflow_artifact


if __name__ == "__main__":
    artifact = run_standard_workflow()
    print(f"Status:  {artifact[\'status\']}")
    print(f"Steps:   {len(artifact[\'steps\'])}")
'''

_STANDARD_README_MD = """\
# Standard Governance Starter -- Approval Checkpoint

Generated by `aigc workflow init --profile standard`.

## Run

```bash
python workflow_example.py
```

Expected output:
```
  [Approval requested] Response to: Draft a proposal for review.
  [Approval simulated] -> APPROVED
Status:  COMPLETED
Steps:   3
```

## What this demonstrates

- 3-step governed workflow with human approval checkpoint
- `session.pause()` -> `session.resume()` lifecycle transitions
- Cancel path when approval is denied (`session.cancel()`)
- Workflow artifact status `COMPLETED` or `CANCELED`

## Customize

1. Replace `_request_human_approval()` with your real approval flow
2. Replace `_simulate_model_call()` with your real model API call
3. Edit `policy.yaml` to add enforcement constraints
"""


def render_standard_starter(role: str = "ai-assistant") -> dict[str, str]:
    """Return {filename: content} for the standard starter profile."""
    preset = StandardPreset(role=role)
    return {
        "policy.yaml": preset.policy_yaml,
        "workflow_example.py": _STANDARD_WORKFLOW_PY.replace("__AIGC_ROLE__", role),
        "README.md": _STANDARD_README_MD,
    }


# ---------------------------------------------------------------------------
# Regulated High Assurance profile (source-required + tool budget)
# ---------------------------------------------------------------------------

_REGULATED_WORKFLOW_PY = '''\
"""
Regulated High Assurance AIGC workflow example.

Generated by: aigc workflow init --profile regulated-high-assurance

Run:
    python workflow_example.py

Demonstrates:
- ProvenanceGate: every invocation must include context.provenance.source_ids
- Tool budget: policy limits document_reader to 3 calls per invocation
No external model API required.
"""
import aigc
from aigc import ProvenanceGate


def _simulate_model_call(prompt: str) -> dict:
    """Simulated model response. Replace with your real model call."""
    return {"result": f"Response to: {prompt[:60]}"}


def run_regulated_workflow(policy_file: str = "policy.yaml") -> dict:
    """Run a 2-step source-required workflow. Returns the workflow artifact."""
    # ProvenanceGate requires context.provenance.source_ids in every invocation.
    gate = ProvenanceGate(require_source_ids=True)
    governance = aigc.AIGC(custom_gates=[gate])

    with governance.open_session(policy_file=policy_file) as session:
        # --- Step 1: Source-bound analysis ---
        pre1 = session.enforce_step_pre_call({
            "policy_file": policy_file,
            "input": {"prompt": "Analyze these source documents."},
            "output": {},
            "context": {
                "provenance": {
                    "source_ids": ["doc-001", "doc-002"],
                },
            },
            "tool_calls": [
                {"name": "document_reader", "call_id": "tc-1"},
            ],
            "model_provider": "anthropic",
            "model_identifier": "claude-sonnet-4-6",
            "role": "__AIGC_ROLE__",
        })
        output1 = _simulate_model_call("Analyze these source documents.")
        session.enforce_step_post_call(pre1, output1)

        # --- Step 2: Source-bound summary ---
        pre2 = session.enforce_step_pre_call({
            "policy_file": policy_file,
            "input": {"prompt": "Summarize the analysis."},
            "output": {},
            "context": {
                "provenance": {
                    "source_ids": ["analysis-step-1"],
                },
            },
            "model_provider": "anthropic",
            "model_identifier": "claude-sonnet-4-6",
            "role": "__AIGC_ROLE__",
        })
        output2 = _simulate_model_call("Summarize the analysis.")
        session.enforce_step_post_call(pre2, output2)

        session.complete()

    return session.workflow_artifact


if __name__ == "__main__":
    artifact = run_regulated_workflow()
    print(f"Status:  {artifact[\'status\']}")
    print(f"Steps:   {len(artifact[\'steps\'])}")
'''

_REGULATED_README_MD = """\
# Regulated High Assurance Starter -- Source-Required with Tool Budget

Generated by `aigc workflow init --profile regulated-high-assurance`.

## Run

```bash
python workflow_example.py
```

Expected output:
```
Status:  COMPLETED
Steps:   2
```

## What this demonstrates

- `ProvenanceGate`: every invocation must include `context.provenance.source_ids`
- Tool budget enforcement: `policy.yaml` limits `document_reader` to 3 calls per step
- Missing source IDs -> `CustomGateViolationError` (fail-closed by default)

## Customize

1. Replace `_simulate_model_call()` with your real model API call
2. Update `source_ids` in each invocation context to reflect your real source documents
3. Adjust `tool_calls` to match your actual tool usage (stay within `max_calls: 3`)
4. Edit `policy.yaml` to add more tools or tighten limits
"""


def render_regulated_starter(role: str = "ai-assistant") -> dict[str, str]:
    """Return {filename: content} for the regulated-high-assurance starter profile."""
    preset = RegulatedHighAssurancePreset(role=role)
    return {
        "policy.yaml": preset.policy_yaml,
        "workflow_example.py": _REGULATED_WORKFLOW_PY.replace("__AIGC_ROLE__", role),
        "README.md": _REGULATED_README_MD,
    }
