"""
workflow lint — static diagnostics for AIGC governance targets.

Supported target kinds:
- ``policy``         — a YAML policy file
- ``starter_dir``    — a directory generated by ``aigc workflow init``
- ``workflow_artifact`` — a JSON workflow artifact
- ``audit_artifact`` — a JSON invocation audit artifact

Each public function returns a list of finding dicts:
    {
        "code":        str,   # machine-readable code (e.g. "POLICY_LOAD_ERROR")
        "message":     str,   # human-readable description
        "target_kind": str,   # "policy" | "starter_dir" | "workflow_artifact" | "audit_artifact"
        "path":        str,   # absolute path that was checked
    }

An empty list means the target is clean.
"""

from __future__ import annotations

import ast
import json
import re
from pathlib import Path
from typing import Any

import yaml
from jsonschema import Draft7Validator

from aigc._internal.policy_loader import SCHEMAS_DIR


# ---------------------------------------------------------------------------
# Schema loading (lazy, cached at module level)
# ---------------------------------------------------------------------------

_POLICY_SCHEMA: dict | None = None
_WORKFLOW_SCHEMA: dict | None = None
_AUDIT_SCHEMA: dict | None = None


def _policy_schema() -> dict:
    global _POLICY_SCHEMA
    if _POLICY_SCHEMA is None:
        path = SCHEMAS_DIR / "policy_dsl.schema.json"
        _POLICY_SCHEMA = json.loads(path.read_text(encoding="utf-8"))
    return _POLICY_SCHEMA


def _workflow_schema() -> dict:
    global _WORKFLOW_SCHEMA
    if _WORKFLOW_SCHEMA is None:
        path = SCHEMAS_DIR / "workflow_artifact.schema.json"
        _WORKFLOW_SCHEMA = json.loads(path.read_text(encoding="utf-8"))
    return _WORKFLOW_SCHEMA


def _audit_schema() -> dict:
    global _AUDIT_SCHEMA
    if _AUDIT_SCHEMA is None:
        path = SCHEMAS_DIR / "audit_artifact.schema.json"
        _AUDIT_SCHEMA = json.loads(path.read_text(encoding="utf-8"))
    return _AUDIT_SCHEMA


# ---------------------------------------------------------------------------
# Finding constructor
# ---------------------------------------------------------------------------

def _finding(code: str, message: str, target_kind: str, path: str) -> dict:
    return {"code": code, "message": message, "target_kind": target_kind, "path": path}


# ---------------------------------------------------------------------------
# Auto-detection of target kind
# ---------------------------------------------------------------------------

def detect_target_kind(path: str) -> str:
    """
    Infer the target kind from path.

    Returns one of: "policy", "starter_dir", "workflow_artifact", "audit_artifact",
    or "unknown" if no match.
    """
    p = Path(path)
    if not p.exists():
        return "unknown"

    if p.is_dir():
        has_policy = (p / "policy.yaml").is_file()
        has_workflow = (p / "workflow_example.py").is_file()
        has_readme = (p / "README.md").is_file()
        if has_policy and has_workflow and has_readme:
            return "starter_dir"
        return "unknown"

    suffix = p.suffix.lower()
    if suffix in (".yaml", ".yml"):
        return "policy"

    if suffix == ".json":
        try:
            raw = json.loads(p.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return "unknown"
        if isinstance(raw, dict) and raw.get("artifact_type") == "workflow":
            return "workflow_artifact"
        # Check against audit schema shape (required fields)
        if isinstance(raw, dict) and "enforcement_result" in raw and "audit_schema_version" in raw:
            return "audit_artifact"
        return "unknown"

    return "unknown"


# ---------------------------------------------------------------------------
# Policy lint
# ---------------------------------------------------------------------------

def lint_policy(path: str, *, target_kind: str = "policy") -> list[dict]:
    """
    Lint a policy YAML file.

    Checks performed:
    1. File readability
    2. YAML parse
    3. Root must be a mapping
    4. JSON-schema validation against policy_dsl.schema.json
    5. Date consistency: effective_date <= expiration_date
    6. Duplicate entries in tools.allowed_tools
    7. output_schema must itself be a valid Draft 7 JSON schema
    """
    findings: list[dict] = []
    p = Path(path)

    # 1. Readability
    try:
        raw = p.read_text(encoding="utf-8")
    except OSError as exc:
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            f"Cannot read policy file: {exc}",
            target_kind,
            str(p),
        ))
        return findings

    # 2. YAML parse
    try:
        policy = yaml.safe_load(raw)
    except yaml.YAMLError as exc:
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            f"YAML parse error: {exc}",
            target_kind,
            str(p),
        ))
        return findings

    # 3. Root type
    if not isinstance(policy, dict):
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            "Policy file must be a YAML mapping (dict), got "
            f"{type(policy).__name__}.",
            target_kind,
            str(p),
        ))
        return findings

    # 4. JSON-schema validation
    schema = _policy_schema()
    validator = Draft7Validator(schema)
    schema_errors = sorted(validator.iter_errors(policy), key=lambda e: list(e.path))
    for err in schema_errors:
        pointer = ".".join(str(seg) for seg in err.absolute_path) or "$"
        findings.append(_finding(
            "POLICY_SCHEMA_VALIDATION_ERROR",
            f"Schema violation at {pointer}: {err.message}",
            target_kind,
            str(p),
        ))
    if findings:
        return findings

    # 5. Date consistency
    eff = policy.get("effective_date")
    exp = policy.get("expiration_date")
    if eff and exp and eff > exp:
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            f"effective_date ({eff}) is after expiration_date ({exp}); "
            "policy can never be valid.",
            target_kind,
            str(p),
        ))

    # 6. Duplicate tool names in tools.allowed_tools
    tools_section = policy.get("tools", {})
    allowed_tools = (
        tools_section.get("allowed_tools", []) if isinstance(tools_section, dict) else []
    )
    seen: list[str] = []
    for tool in (allowed_tools or []):
        if not isinstance(tool, dict):
            continue
        name = tool.get("name", "")
        if name in seen:
            findings.append(_finding(
                "TOOL_CONSTRAINT_VIOLATION",
                f"Duplicate tool name in tools.allowed_tools: '{name}'.",
                target_kind,
                str(p),
            ))
        else:
            seen.append(name)

    # 7. output_schema well-formedness
    output_schema = policy.get("output_schema")
    if output_schema is not None and isinstance(output_schema, dict):
        try:
            Draft7Validator.check_schema(output_schema)
        except Exception as exc:
            findings.append(_finding(
                "POLICY_SCHEMA_VALIDATION_ERROR",
                f"output_schema is not a valid JSON Schema Draft 7: {exc}",
                target_kind,
                str(p),
            ))

    return findings


# ---------------------------------------------------------------------------
# Starter directory lint
# ---------------------------------------------------------------------------

_INTERNAL_IMPORT_RE = re.compile(
    r"(?:^|\n)\s*(?:from|import)\s+aigc\._internal"
)


def lint_starter_dir(path: str) -> list[dict]:
    """
    Lint a starter directory generated by ``aigc workflow init``.

    Checks:
    - Required files exist (policy.yaml, workflow_example.py, README.md)
    - All required files are non-empty
    - policy.yaml passes policy lint
    - workflow_example.py parses as valid Python (AST)
    - workflow_example.py does not import aigc._internal
    """
    findings: list[dict] = []
    p = Path(path)

    required_files = ["policy.yaml", "workflow_example.py", "README.md"]
    for fname in required_files:
        fpath = p / fname
        if not fpath.is_file():
            findings.append(_finding(
                "WORKFLOW_STARTER_INTEGRITY_ERROR",
                f"Required file '{fname}' is missing from starter directory.",
                "starter_dir",
                str(p),
            ))
            continue
        if fpath.stat().st_size == 0:
            findings.append(_finding(
                "WORKFLOW_STARTER_INTEGRITY_ERROR",
                f"Required file '{fname}' is empty.",
                "starter_dir",
                str(p),
            ))

    # Stop here if files are missing — subsequent checks will error
    if any(f["code"] == "WORKFLOW_STARTER_INTEGRITY_ERROR" for f in findings):
        return findings

    # Lint nested policy.yaml
    nested_policy = str(p / "policy.yaml")
    policy_findings = lint_policy(nested_policy, target_kind="starter_dir")
    findings.extend(policy_findings)

    # Validate workflow_example.py
    workflow_py = p / "workflow_example.py"
    try:
        source = workflow_py.read_text(encoding="utf-8")
    except OSError as exc:
        findings.append(_finding(
            "WORKFLOW_STARTER_INTEGRITY_ERROR",
            f"Cannot read workflow_example.py: {exc}",
            "starter_dir",
            str(p),
        ))
        return findings

    # AST parse check
    try:
        ast.parse(source)
    except SyntaxError as exc:
        findings.append(_finding(
            "WORKFLOW_STARTER_INTEGRITY_ERROR",
            f"workflow_example.py has a syntax error: {exc}",
            "starter_dir",
            str(p),
        ))

    # Public-import safety check
    if _INTERNAL_IMPORT_RE.search(source):
        findings.append(_finding(
            "WORKFLOW_STARTER_INTEGRITY_ERROR",
            "workflow_example.py imports from aigc._internal, which is not "
            "part of the public API. Use public aigc imports only.",
            "starter_dir",
            str(p),
        ))

    return findings


# ---------------------------------------------------------------------------
# Workflow artifact lint
# ---------------------------------------------------------------------------

def lint_workflow_artifact(path: str) -> list[dict]:
    """
    Lint a serialized workflow artifact JSON file.

    Checks:
    - JSON parse
    - Schema validation against workflow_artifact.schema.json
    - len(invocation_audit_checksums) == len(steps)
    - failure_summary present for FAILED artifacts, absent/null for others
    """
    findings: list[dict] = []
    p = Path(path)

    # JSON parse
    try:
        raw = p.read_text(encoding="utf-8")
    except OSError as exc:
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            f"Cannot read workflow artifact: {exc}",
            "workflow_artifact",
            str(p),
        ))
        return findings

    try:
        artifact: Any = json.loads(raw)
    except json.JSONDecodeError as exc:
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            f"JSON parse error in workflow artifact: {exc}",
            "workflow_artifact",
            str(p),
        ))
        return findings

    if not isinstance(artifact, dict):
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            "Workflow artifact must be a JSON object.",
            "workflow_artifact",
            str(p),
        ))
        return findings

    # Schema validation
    schema = _workflow_schema()
    validator = Draft7Validator(schema)
    schema_errors = sorted(validator.iter_errors(artifact), key=lambda e: list(e.path))
    for err in schema_errors:
        pointer = ".".join(str(seg) for seg in err.absolute_path) or "$"
        findings.append(_finding(
            "POLICY_SCHEMA_VALIDATION_ERROR",
            f"Workflow artifact schema violation at {pointer}: {err.message}",
            "workflow_artifact",
            str(p),
        ))
    if findings:
        return findings

    # Checksum / step count consistency
    steps = artifact.get("steps", [])
    checksums = artifact.get("invocation_audit_checksums", [])
    if len(checksums) != len(steps):
        findings.append(_finding(
            "WORKFLOW_STARTER_INTEGRITY_ERROR",
            f"invocation_audit_checksums length ({len(checksums)}) does not "
            f"match steps length ({len(steps)}). Artifact may be corrupt.",
            "workflow_artifact",
            str(p),
        ))

    # failure_summary consistency
    status = artifact.get("status", "")
    failure_summary = artifact.get("failure_summary")
    if status == "FAILED" and not failure_summary:
        findings.append(_finding(
            "WORKFLOW_STARTER_INTEGRITY_ERROR",
            "Workflow artifact has status FAILED but failure_summary is "
            "absent or null. Artifact may be incomplete.",
            "workflow_artifact",
            str(p),
        ))
    elif status != "FAILED" and failure_summary is not None:
        findings.append(_finding(
            "WORKFLOW_STARTER_INTEGRITY_ERROR",
            f"Workflow artifact has status {status!r} but failure_summary "
            "is non-null. Unexpected state.",
            "workflow_artifact",
            str(p),
        ))

    return findings


# ---------------------------------------------------------------------------
# Audit artifact lint
# ---------------------------------------------------------------------------

def lint_audit_artifact(path: str, *, target_kind: str = "audit_artifact") -> list[dict]:
    """
    Lint an invocation audit artifact JSON file.

    Checks performed:
    1. File readability
    2. JSON parse
    3. Root must be a JSON object
    4. JSON-schema validation against audit_artifact.schema.json
    """
    findings: list[dict] = []
    p = Path(path)

    try:
        raw = p.read_text(encoding="utf-8")
    except OSError as exc:
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            f"Cannot read audit artifact: {exc}",
            target_kind,
            str(p),
        ))
        return findings

    try:
        artifact = json.loads(raw)
    except json.JSONDecodeError as exc:
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            f"JSON parse error in audit artifact: {exc}",
            target_kind,
            str(p),
        ))
        return findings

    if not isinstance(artifact, dict):
        findings.append(_finding(
            "POLICY_LOAD_ERROR",
            "Audit artifact must be a JSON object.",
            target_kind,
            str(p),
        ))
        return findings

    schema = _audit_schema()
    validator = Draft7Validator(schema)
    schema_errors = sorted(validator.iter_errors(artifact), key=lambda e: list(e.path))
    for err in schema_errors:
        pointer = ".".join(str(seg) for seg in err.absolute_path) or "$"
        findings.append(_finding(
            "POLICY_SCHEMA_VALIDATION_ERROR",
            f"Audit artifact schema violation at {pointer}: {err.message}",
            target_kind,
            str(p),
        ))

    return findings


# ---------------------------------------------------------------------------
# Unified entry-point
# ---------------------------------------------------------------------------

def lint_target(path: str, *, kind: str = "auto") -> list[dict]:
    """
    Lint any supported target.

    Args:
        path: Path to the target (file or directory).
        kind: One of "auto", "policy", "starter_dir", "workflow_artifact",
              or "audit_artifact".
              When "auto", the kind is inferred from the path.

    Returns:
        List of finding dicts (empty = clean).
    """
    if kind == "auto":
        kind = detect_target_kind(path)

    if kind == "policy":
        return lint_policy(path)
    elif kind == "starter_dir":
        return lint_starter_dir(path)
    elif kind == "workflow_artifact":
        return lint_workflow_artifact(path)
    elif kind == "audit_artifact":
        return lint_audit_artifact(path)
    else:
        return [_finding(
            "POLICY_LOAD_ERROR",
            f"Cannot determine target kind for: {path}. "
            "Supported targets: .yaml/.yml policy files, starter directories "
            "(containing policy.yaml + workflow_example.py + README.md), "
            "workflow artifact .json files, and invocation audit artifact "
            ".json files.",
            "unknown",
            path,
        )]
